name: Build font and specimen

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v5
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install Linux dependencies
      run: |
        sudo snap install yq
    - name: Build font
      run: make build
    - name: Check with fontbakery
      run: make test
      continue-on-error: true
    - name: Generate proofs
      run: make proof
    - name: Gather
      run: |
          mkdir for-gh-pages
          mv fontbakery-report.html for-gh-pages
          mv proof/* for-gh-pages
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
          for-gh-pages
    - name: Remove temp folder
      run: |
          rm -rf for-gh-pages
